AUTH0_CLIENT_ID = 'zWJfWgsOelcUY1yYwupvofc2oCr7JO52'
AUTH0_CLIENT_SECRET = 'YBV-ywAAlOWdLmJQaokgRJqeIdIEfmfINcqYkRpDliy9SojmXCxZ1VEjT3yTb-6p'
AUTH0_CALLBACK_URL = 'http://localhost:5000/callback'
AUTH0_DOMAIN = 'dvcoffee.us.auth0.com'
AUTH0_AUDIENCE = 'http://localhost:4000'
PROFILE_KEY = 'profile'
SECRET_KEY = 'YBV-ywAAlOWdLmJQaokgRJqeIdIEfmfINcqYkRpDliy9SojmXCxZ1VEjT3yTb-6p'
JWT_PAYLOAD = 'jwt_payload'
